import product_template
import partner
import characteristic
import ir_action_inherit
import account_invoice
import stock_picking
import sale
import sale_config
import mv_details
import product
import res_lang
import product_variant
import type_evenement
import evenement
import purchase_order
import wizard
import mv_detail_sol
import charte
import expedition
import stock_move
import claims
import report_stock_move
import users