# coding: utf8
# TODO: Cmo,Reprendre tous les textes de licence dans les fichiers
{
    'name': 'Davidts Base Data',
    'version': '0.1',
    'category': 'Davidts',
    'author': 'Audaxis pour Davidts',
    'description': "Base Data required for Davidts",
    'complexity': 'expert',
    'website': '',
    'depends': ['product_variant_multi'],
    'data': [
         
        'data/res.users.csv',
        'data/res.country.state.csv',
        'data/res.lang.csv',
        'data/res.company.csv',
        'data/res.bank.csv',
        'data/product.variant.dimension.type.csv',
        'data/product.variant.dimension.option.csv',
        'data/account.payment.term.csv',
        'data/product.ul.csv',
        'data/crm.case.section.csv',
        'data/davidts.inner_material.csv',
        'data/davidts.outer_material.csv',
        'data/product.category.csv',
        'data/davidts.metier.csv',
        'data/product.template.csv',
        'data/res.partner.csv',
        'data/dimension_packaging/product.template.csv',
        'data/template_tax/product.template.csv',
        'data/equipe_commerciale/res.partner.csv',
        'data/product_material/product.template.csv',
        'data/supplier/res.partner.csv',
        'data/template_color/product.template.csv',
        'data/shipping/res.partner.csv',
 ],
    'test': [],
    'application': True,
    'auto_install': False,
    'installable': True,
}
