language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --ignore=E501,E225 ."
